### ISSUE TITLE
Support Multiple lighthouse Hosts

### ISSUE THREAD

**Issue by kanniget** [kanniget/nebulamgr#2]
Current approach only supports a single lighthouse instance. 

Need to adjust the code to allow multiple.

**Comment by kanniget** [comment]
Functionality added to support multiple lighthouses.   Needs testing as I dont have multiple.

**Comment by luismanson** [comment]
> Needs testing as I dont have multiple.

It's not working, something is wrong in my definition, i think.

```
Generating configs
     f1.vpn.testingnet.xyz
Traceback (most recent call last):
  File "./nebulamgr.py", line 232, in <module>
    main()
  File "./nebulamgr.py", line 224, in main
    process(args)
  File "./nebulamgr.py", line 189, in process
    build_conf(entry, Config)
  File "./nebulamgr.py", line 141, in build_conf
    lighthouse["address"]=resolveLighthouseAddress(lighthouse["name"], config)
TypeError: list indices must be integers or slices, not str

```

Updated definition
```
cidr: "24"
lighthouse:
    - f1.vpn.testingnet.xyz:
        remote: "one.testingnet.xyz"
        remote_port: "4242"

    - f2.vpn.testingnet.xyz:
        remote: "two.testingnet.xyz"
        remote_port: "4242"

hosts:
    - f1.vpn.testingnet.xyz:
        address: "10.175.17.1"
        port: "4242"
    - f2.vpn.testingnet.xyz:
        address: "10.175.17.2"
        port: "4242"
    - endpoint1.vpn.testingnet.xyz:
        address: "10.175.17.100"
        #localnet: "192.168.0.0/24"
        port: "4242"

```

**Comment by kanniget** [comment]
I am not near my dev environment at the moment but I think the issue is I did not update the sample conf.

I think it should be like this....

cidr: "24"
lighthouse:
    - name: "f1.vpn.testingnet.xyz"
        remote: "one.testingnet.xyz"
        remote_port: "4242"

    - name: "f2.vpn.testingnet.xyz"
        remote: "two.testingnet.xyz"
        remote_port: "4242"

hosts:
    - f1.vpn.testingnet.xyz:
        address: "10.175.17.1"
        port: "4242"
    - f2.vpn.testingnet.xyz:
        address: "10.175.17.2"
        port: "4242"
    - endpoint1.vpn.testingnet.xyz:
        address: "10.175.17.100"
        #localnet: "192.168.0.0/24"
        port: "4242"

**Comment by luismanson** [comment]
Thanks. That did not do it.
Don't you need to loop lighthouses near this line?
` lighthouse["address"]=resolveLighthouseAddress(lighthouse["name"], config)`

**Comment by kanniget** [comment]
I will have to look at it, I setup a test config file and it generates everything ok using the approach I mentioned.

There is a loop on the line before that one to run through the hosts and inside the function it loops through the lighthouses.....

**Comment by luismanson** [comment]
> I will have to look at it, I setup a test config file and it generates everything ok using the approach I mentioned.

Thanks! It's working....Fixed with a git pull... :\

I think I found a missing loop for hosts:
```
  # IMPORTANT2: THIS SHOULD BE LIGHTHOUSES' NEBULA IPs, NOT LIGHTHOUSES' REAL ROUTABLE IPs
  hosts:
    {% for entry in lighthouse %}{% if not is_lighthouse %}- "{{ entry.address }}"  # {{entry.remote}} {% endif %}
    {% endfor %}

```

One question, in "Security/nbound" how's 'destination' field used?

**Comment by kanniget** [comment]
I will take a lookat the loop tonight, currently late for work...

from memory the logic is...
the destination field is the name of the group or host the rule is applied
to..

so when you want to allow a host A to connect to host B you put host B in
the destination....  if you want to host A to connect to Group C then C
goes in the destination field...

**Comment by luismanson** [comment]
In nebulamgr.yml i see a combination of destination, group and host fieldname used...Is this ok? I still don't see where/how destination is evaluated and where it ends up in the config file. I'm always afraid to be asking obvious stuff, but I still do not understand 'a destination' field in 'input chain'? And there is no mention of it in nebula's config file.

Thanks for your help

```
security:
    inbound:
      - port: "any"
        proto: "icmp"
        host:  "any"
        destination: "all"
        comment: " Allow any icmp between nodes "
      - port: "22"
        proto: "tcp"
        group: "management"
        destination: "all"
        comment: " Allow all management servers to connect via port 22 ( SSH )  "

```

Official config.yml

  ```
# The firewall is default deny. There is no way to write a deny rule.
  # Rules are comprised of a protocol, port, and one or more of host, group, or CIDR
  # Logical evaluation is roughly: port AND proto AND (ca_sha OR ca_name) AND (host OR group OR groups OR cidr)
  # - port: Takes `0` or `any` as any, a single number `80`, a range `200-901`, or `fragment` to match second and further fragments of fragmented packets (since there is no port available).
  #   code: same as port but makes more sense when talking about ICMP, TODO: this is not currently implemented in a way that works, use `any`
  #   proto: `any`, `tcp`, `udp`, or `icmp`
  #   host: `any` or a literal hostname, ie `test-host`
  #   group: `any` or a literal group name, ie `default-group`
  #   groups: Same as group but accepts a list of values. Multiple values are AND'd together and a certificate would have to contain all groups to pass
  #   cidr: a CIDR, `0.0.0.0/0` is any.
  #   ca_name: An issuing CA name
  #   ca_sha: An issuing CA shasum

```
